### ISSUE TITLE
Very poor range

### ISSUE THREAD

**Issue by grego1981** [eyalcha/thermal#3]
Using latest latest version from github for the sensor and from HACS for the HA component
## Configuration

```yaml
camera:
  - platform: thermal
    name: lr_thermal
    host: http://10.10.10.43
    min_temp: 20
    max_temp: 45
    mirror: true
sensor:
  - platform: thermal
    host: http://10.10.10.43
    scan_interval: 2
    sensor:
      rows: 8
      cols: 8
    state: max
```

## Describe the bug
The sensor picks up cahnges for up to 60-70cm I'm using the grid-eye sparkfun breakout board on a Wemos D1 clone ESP8266 board. Is there anyhing more I can do to improve the range?
