### ISSUE TITLE
Configuration in ROI

### ISSUE THREAD

**Issue by sanderlv** [eyalcha/thermal#4]
Hi, we are trying to work through your super cool project!

We think we have "some" working but have a question about detecting a "person". We try to use the sensor component in homeassitant but have some problems in understanding how to interpret the "ROI" options.

What if we use your example:
```
    sensor:
      rows: 8
      cols: 8
    roi:
      left: 3
      top: 3
      right: 5
      bottom: 5
```

Will that select the following area? We selected 8 columns in "sensor:"

![image](https://user-images.githubusercontent.com/16528916/114308932-bc2a2900-9ae5-11eb-9247-f9ffe59462a1.png)

Thank you!
